MinGW not defined here - include getcwd also
Error:
../../../supportApp/netCDFSrc/libdispatch/ddispatch.c:87:16: error: implicit declaration of function 'getcwd'; did you mean 'getw'? [-Werror=implicit-function-declaration]
      tempdir = getcwd(cwd,sizeof(cwd));

As the headers are only included if MSC_VER (VStudio) is defined when actually both MinGW and VStudio contain these:
https://www.gnu.org/software/gnulib/manual/html_node/getcwd.html