Fix define of VStudio regardless of MinGW build
Similar to this issue: https://github.com/urho3d/Urho3D/issues/1444
Redefinition of timespec and timezone in H5win32defs.h because H5_HAVE_VISUAL_STUDIO is always defined regardless of any factors - throws errors below when running a MinGW build:
In file included from ../H5private.h:607:0,
                 from ../H5.c:22:
../H5win32defs.h:81:8: error: redefinition of 'struct timezone'
 struct timezone {
        ^~~~~~~~
In file included from ../H5private.h:109:0,
                 from ../H5.c:22:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/time.h:259:8: note: originally defined here
 struct timezone {
        ^~~~~~~~
In file included from ../H5private.h:607:0,
                 from ../H5.c:22:
../H5win32defs.h:88:8: error: redefinition of 'struct timespec'
 struct timespec
        ^~~~~~~~
In file included from ../os/default/H5public.h:38:0,
                 from ../H5private.h:27,
                 from ../H5.c:22: