case sensitivity on linux causes cross compile fail
Ran into this issue when using MinGW on linux to cross compile for windows. Courtesy solution by:
https://stackoverflow.com/questions/40729241/winsock2-h-seems-to-be-missing-from-mingw

Error found:
../H5Zlz4.c:13:10: fatal error: Winsock2.h: No such file or directory
 #include <Winsock2.h>